baseURL = "https://rfc.vac.dev"
languageCode = "en-us"
title = "Vac RFC"
theme = "book"

[params]
BookMenuBundle = "/menu"

[permalinks]
  docs = "/spec/:slug"

[markup.tableOfContents]
  startLevel = 1
