title: "Vac Protocol"

markdown: kramdown
theme: minima

collections:
  specs:
    output: true

defaults:
  -
    scope:
      path: "specs"
    values:
      layout: "spec"

header_pages:
  - waku.md
  
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
