pipeline {
  agent {
    dockerfile {
      label 'linux'
      dir 'ci'
    }
  }

  options {
    timestamps()
    timeout(time: 5, unit: 'MINUTES')
    disableConcurrentBuilds()
    buildDiscarder(logRotator(
      numToKeepStr: '20',
      daysToKeepStr: '30',
    ))
  }

  environment {
    GIT_COMMITTER_NAME = 'status-im-auto'
    GIT_COMMITTER_EMAIL = 'auto@status.im'
    GIT_SSH_COMMAND = 'ssh -o StrictHostKeyChecking=no'
  }

  stages {
    stage('Build') {
      steps {
        sh 'hugo'
      }
    }

    stage('Publish Prod') {
      steps {
        sshagent(credentials: ['status-im-auto-ssh']) {
          sh 'ghp-import -p public'
        }
      }
    }
  }

  post {
    cleanup { cleanWs() }
  }
}
